language: node_js
sudo: false
install:
  - "npm install -g n"
  - "npm install"
script:
  - "ls $(npm prefix -g)/bin"
  - "gulp travis"
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "iojs-v1"
  - "iojs-v2"
  - "iojs-v3"
cache:
  directories:
    - "node_modules"
