language: node_js
sudo: false
install:
  - "curl -L http://git.io/n-install | bash"
  - "npm install"
script:
  - "gulp travis"
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "iojs-v1"
  - "iojs-v2"
  - "iojs-v3"
cache:
  directories:
    - "node_modules"
